export const brandingPanel: string
export const fullHeight: string
export const image: string
export const legalNotice: string
export const loginFormArea: string
export const loginFormButton: string
export const loginFormForgot: string
export const portalTitle: string
export const sidebar: string
export const sidebarRightContent: string
export const title: string
export const welcomeBackArea: string
export const welcomeBackText: string
