//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpJobs.CakeV10 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cakemarketing.com/api/10/", ConfigurationName="CakeV10.reportsSoap")]
    public interface reportsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cakemarketing.com/api/10/Conversions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(base_response))]
        IpJobs.CakeV10.conversion_report_response Conversions(string api_key, System.DateTime start_date, System.DateTime end_date, int affiliate_id, int advertiser_id, int offer_id, int campaign_id, int creative_id, bool include_tests, int start_at_row, int row_limit, IpJobs.CakeV10.ConversionsSortFields sort_field, bool sort_descending);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cakemarketing.com/api/10/Conversions", ReplyAction="*")]
        System.Threading.Tasks.Task<IpJobs.CakeV10.conversion_report_response> ConversionsAsync(string api_key, System.DateTime start_date, System.DateTime end_date, int affiliate_id, int advertiser_id, int offer_id, int campaign_id, int creative_id, bool include_tests, int start_at_row, int row_limit, IpJobs.CakeV10.ConversionsSortFields sort_field, bool sort_descending);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cakemarketing.com/api/10/ConversionChanges", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(base_response))]
        IpJobs.CakeV10.conversion_report_response ConversionChanges(string api_key, System.DateTime changes_since, bool include_new_conversions, int affiliate_id, int advertiser_id, int offer_id, int campaign_id, int creative_id, bool include_tests, int start_at_row, int row_limit, IpJobs.CakeV10.ConversionsSortFields sort_field, bool sort_descending);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cakemarketing.com/api/10/ConversionChanges", ReplyAction="*")]
        System.Threading.Tasks.Task<IpJobs.CakeV10.conversion_report_response> ConversionChangesAsync(string api_key, System.DateTime changes_since, bool include_new_conversions, int affiliate_id, int advertiser_id, int offer_id, int campaign_id, int creative_id, bool include_tests, int start_at_row, int row_limit, IpJobs.CakeV10.ConversionsSortFields sort_field, bool sort_descending);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cakemarketing.com/api/10/Clicks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(base_response))]
        IpJobs.CakeV10.click_report_response Clicks(string api_key, System.DateTime start_date, System.DateTime end_date, int affiliate_id, int advertiser_id, int offer_id, int campaign_id, int creative_id, byte price_format_id, bool include_duplicates, bool include_tests, int start_at_row, int row_limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cakemarketing.com/api/10/Clicks", ReplyAction="*")]
        System.Threading.Tasks.Task<IpJobs.CakeV10.click_report_response> ClicksAsync(string api_key, System.DateTime start_date, System.DateTime end_date, int affiliate_id, int advertiser_id, int offer_id, int campaign_id, int creative_id, byte price_format_id, bool include_duplicates, bool include_tests, int start_at_row, int row_limit);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/api/10/")]
    public enum ConversionsSortFields {
        
        /// <remarks/>
        conversion_id,
        
        /// <remarks/>
        visitor_id,
        
        /// <remarks/>
        request_session_id,
        
        /// <remarks/>
        click_id,
        
        /// <remarks/>
        conversion_date,
        
        /// <remarks/>
        transaction_id,
        
        /// <remarks/>
        last_updated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/api/10/")]
    public partial class conversion_report_response : get_response {
        
        private conversion[] conversionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public conversion[] conversions {
            get {
                return this.conversionsField;
            }
            set {
                this.conversionsField = value;
                this.RaisePropertyChanged("conversions");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/api/10/")]
    public partial class conversion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string conversion_idField;
        
        private int visitor_idField;
        
        private int request_session_idField;
        
        private System.Nullable<int> click_request_session_idField;
        
        private System.Nullable<int> click_idField;
        
        private System.DateTime conversion_dateField;
        
        private System.Nullable<System.DateTime> last_updatedField;
        
        private System.Nullable<System.DateTime> click_dateField;
        
        private affiliate affiliateField;
        
        private advertiser advertiserField;
        
        private offer offerField;
        
        private offer_contract offer_contractField;
        
        private int campaign_idField;
        
        private creative creativeField;
        
        private string sub_id_1Field;
        
        private string sub_id_2Field;
        
        private string sub_id_3Field;
        
        private string sub_id_4Field;
        
        private string sub_id_5Field;
        
        private string conversion_typeField;
        
        private payment paidField;
        
        private payment receivedField;
        
        private byte step_reachedField;
        
        private bool pixel_droppedField;
        
        private bool suppressedField;
        
        private bool returnedField;
        
        private bool testField;
        
        private string transaction_idField;
        
        private string conversion_ip_addressField;
        
        private string click_ip_addressField;
        
        private string conversion_referrer_urlField;
        
        private string click_referrer_urlField;
        
        private string search_termField;
        
        private string conversion_user_agentField;
        
        private string click_user_agentField;
        
        private country countryField;
        
        private region regionField;
        
        private language languageField;
        
        private isp ispField;
        
        private device deviceField;
        
        private operating_system operating_systemField;
        
        private browser browserField;
        
        private disposition current_dispositionField;
        
        private campaign_type campaign_typeField;
        
        private payment order_totalField;
        
        private string storefrontField;
        
        private string payout_rule_nameField;
        
        private string noteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string conversion_id {
            get {
                return this.conversion_idField;
            }
            set {
                this.conversion_idField = value;
                this.RaisePropertyChanged("conversion_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int visitor_id {
            get {
                return this.visitor_idField;
            }
            set {
                this.visitor_idField = value;
                this.RaisePropertyChanged("visitor_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int request_session_id {
            get {
                return this.request_session_idField;
            }
            set {
                this.request_session_idField = value;
                this.RaisePropertyChanged("request_session_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> click_request_session_id {
            get {
                return this.click_request_session_idField;
            }
            set {
                this.click_request_session_idField = value;
                this.RaisePropertyChanged("click_request_session_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> click_id {
            get {
                return this.click_idField;
            }
            set {
                this.click_idField = value;
                this.RaisePropertyChanged("click_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime conversion_date {
            get {
                return this.conversion_dateField;
            }
            set {
                this.conversion_dateField = value;
                this.RaisePropertyChanged("conversion_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> last_updated {
            get {
                return this.last_updatedField;
            }
            set {
                this.last_updatedField = value;
                this.RaisePropertyChanged("last_updated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> click_date {
            get {
                return this.click_dateField;
            }
            set {
                this.click_dateField = value;
                this.RaisePropertyChanged("click_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public affiliate affiliate {
            get {
                return this.affiliateField;
            }
            set {
                this.affiliateField = value;
                this.RaisePropertyChanged("affiliate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public advertiser advertiser {
            get {
                return this.advertiserField;
            }
            set {
                this.advertiserField = value;
                this.RaisePropertyChanged("advertiser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public offer offer {
            get {
                return this.offerField;
            }
            set {
                this.offerField = value;
                this.RaisePropertyChanged("offer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public offer_contract offer_contract {
            get {
                return this.offer_contractField;
            }
            set {
                this.offer_contractField = value;
                this.RaisePropertyChanged("offer_contract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int campaign_id {
            get {
                return this.campaign_idField;
            }
            set {
                this.campaign_idField = value;
                this.RaisePropertyChanged("campaign_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public creative creative {
            get {
                return this.creativeField;
            }
            set {
                this.creativeField = value;
                this.RaisePropertyChanged("creative");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string sub_id_1 {
            get {
                return this.sub_id_1Field;
            }
            set {
                this.sub_id_1Field = value;
                this.RaisePropertyChanged("sub_id_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string sub_id_2 {
            get {
                return this.sub_id_2Field;
            }
            set {
                this.sub_id_2Field = value;
                this.RaisePropertyChanged("sub_id_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string sub_id_3 {
            get {
                return this.sub_id_3Field;
            }
            set {
                this.sub_id_3Field = value;
                this.RaisePropertyChanged("sub_id_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string sub_id_4 {
            get {
                return this.sub_id_4Field;
            }
            set {
                this.sub_id_4Field = value;
                this.RaisePropertyChanged("sub_id_4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string sub_id_5 {
            get {
                return this.sub_id_5Field;
            }
            set {
                this.sub_id_5Field = value;
                this.RaisePropertyChanged("sub_id_5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string conversion_type {
            get {
                return this.conversion_typeField;
            }
            set {
                this.conversion_typeField = value;
                this.RaisePropertyChanged("conversion_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public payment paid {
            get {
                return this.paidField;
            }
            set {
                this.paidField = value;
                this.RaisePropertyChanged("paid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public payment received {
            get {
                return this.receivedField;
            }
            set {
                this.receivedField = value;
                this.RaisePropertyChanged("received");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public byte step_reached {
            get {
                return this.step_reachedField;
            }
            set {
                this.step_reachedField = value;
                this.RaisePropertyChanged("step_reached");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public bool pixel_dropped {
            get {
                return this.pixel_droppedField;
            }
            set {
                this.pixel_droppedField = value;
                this.RaisePropertyChanged("pixel_dropped");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public bool suppressed {
            get {
                return this.suppressedField;
            }
            set {
                this.suppressedField = value;
                this.RaisePropertyChanged("suppressed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public bool returned {
            get {
                return this.returnedField;
            }
            set {
                this.returnedField = value;
                this.RaisePropertyChanged("returned");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public bool test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
                this.RaisePropertyChanged("test");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string transaction_id {
            get {
                return this.transaction_idField;
            }
            set {
                this.transaction_idField = value;
                this.RaisePropertyChanged("transaction_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string conversion_ip_address {
            get {
                return this.conversion_ip_addressField;
            }
            set {
                this.conversion_ip_addressField = value;
                this.RaisePropertyChanged("conversion_ip_address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string click_ip_address {
            get {
                return this.click_ip_addressField;
            }
            set {
                this.click_ip_addressField = value;
                this.RaisePropertyChanged("click_ip_address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string conversion_referrer_url {
            get {
                return this.conversion_referrer_urlField;
            }
            set {
                this.conversion_referrer_urlField = value;
                this.RaisePropertyChanged("conversion_referrer_url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string click_referrer_url {
            get {
                return this.click_referrer_urlField;
            }
            set {
                this.click_referrer_urlField = value;
                this.RaisePropertyChanged("click_referrer_url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string search_term {
            get {
                return this.search_termField;
            }
            set {
                this.search_termField = value;
                this.RaisePropertyChanged("search_term");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string conversion_user_agent {
            get {
                return this.conversion_user_agentField;
            }
            set {
                this.conversion_user_agentField = value;
                this.RaisePropertyChanged("conversion_user_agent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string click_user_agent {
            get {
                return this.click_user_agentField;
            }
            set {
                this.click_user_agentField = value;
                this.RaisePropertyChanged("click_user_agent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public country country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public region region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public language language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public isp isp {
            get {
                return this.ispField;
            }
            set {
                this.ispField = value;
                this.RaisePropertyChanged("isp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public device device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
                this.RaisePropertyChanged("device");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public operating_system operating_system {
            get {
                return this.operating_systemField;
            }
            set {
                this.operating_systemField = value;
                this.RaisePropertyChanged("operating_system");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public browser browser {
            get {
                return this.browserField;
            }
            set {
                this.browserField = value;
                this.RaisePropertyChanged("browser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public disposition current_disposition {
            get {
                return this.current_dispositionField;
            }
            set {
                this.current_dispositionField = value;
                this.RaisePropertyChanged("current_disposition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public campaign_type campaign_type {
            get {
                return this.campaign_typeField;
            }
            set {
                this.campaign_typeField = value;
                this.RaisePropertyChanged("campaign_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public payment order_total {
            get {
                return this.order_totalField;
            }
            set {
                this.order_totalField = value;
                this.RaisePropertyChanged("order_total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string storefront {
            get {
                return this.storefrontField;
            }
            set {
                this.storefrontField = value;
                this.RaisePropertyChanged("storefront");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string payout_rule_name {
            get {
                return this.payout_rule_nameField;
            }
            set {
                this.payout_rule_nameField = value;
                this.RaisePropertyChanged("payout_rule_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("note");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class affiliate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int affiliate_idField;
        
        private string affiliate_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int affiliate_id {
            get {
                return this.affiliate_idField;
            }
            set {
                this.affiliate_idField = value;
                this.RaisePropertyChanged("affiliate_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string affiliate_name {
            get {
                return this.affiliate_nameField;
            }
            set {
                this.affiliate_nameField = value;
                this.RaisePropertyChanged("affiliate_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="campaign_type", Namespace="http://cakemarketing.com/api/10/")]
    public partial class campaign_type1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte campaign_type_idField;
        
        private string campaign_type_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public byte campaign_type_id {
            get {
                return this.campaign_type_idField;
            }
            set {
                this.campaign_type_idField = value;
                this.RaisePropertyChanged("campaign_type_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string campaign_type_name {
            get {
                return this.campaign_type_nameField;
            }
            set {
                this.campaign_type_nameField = value;
                this.RaisePropertyChanged("campaign_type_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/api/10/")]
    public partial class campaign : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int campaign_idField;
        
        private string campaign_third_party_nameField;
        
        private campaign_type1 campaign_typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int campaign_id {
            get {
                return this.campaign_idField;
            }
            set {
                this.campaign_idField = value;
                this.RaisePropertyChanged("campaign_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string campaign_third_party_name {
            get {
                return this.campaign_third_party_nameField;
            }
            set {
                this.campaign_third_party_nameField = value;
                this.RaisePropertyChanged("campaign_third_party_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public campaign_type1 campaign_type {
            get {
                return this.campaign_typeField;
            }
            set {
                this.campaign_typeField = value;
                this.RaisePropertyChanged("campaign_type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class site_offer_contract : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int site_offer_contract_idField;
        
        private string site_offer_contract_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int site_offer_contract_id {
            get {
                return this.site_offer_contract_idField;
            }
            set {
                this.site_offer_contract_idField = value;
                this.RaisePropertyChanged("site_offer_contract_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string site_offer_contract_name {
            get {
                return this.site_offer_contract_nameField;
            }
            set {
                this.site_offer_contract_nameField = value;
                this.RaisePropertyChanged("site_offer_contract_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class site_offer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int site_offer_idField;
        
        private string site_offer_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int site_offer_id {
            get {
                return this.site_offer_idField;
            }
            set {
                this.site_offer_idField = value;
                this.RaisePropertyChanged("site_offer_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string site_offer_name {
            get {
                return this.site_offer_nameField;
            }
            set {
                this.site_offer_nameField = value;
                this.RaisePropertyChanged("site_offer_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class brand_advertiser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int brand_advertiser_idField;
        
        private string brand_advertiser_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int brand_advertiser_id {
            get {
                return this.brand_advertiser_idField;
            }
            set {
                this.brand_advertiser_idField = value;
                this.RaisePropertyChanged("brand_advertiser_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string brand_advertiser_name {
            get {
                return this.brand_advertiser_nameField;
            }
            set {
                this.brand_advertiser_nameField = value;
                this.RaisePropertyChanged("brand_advertiser_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class source_affiliate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int source_affiliate_idField;
        
        private string source_affiliate_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int source_affiliate_id {
            get {
                return this.source_affiliate_idField;
            }
            set {
                this.source_affiliate_idField = value;
                this.RaisePropertyChanged("source_affiliate_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string source_affiliate_name {
            get {
                return this.source_affiliate_nameField;
            }
            set {
                this.source_affiliate_nameField = value;
                this.RaisePropertyChanged("source_affiliate_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class channel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<byte> channel_idField;
        
        private string channel_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<byte> channel_id {
            get {
                return this.channel_idField;
            }
            set {
                this.channel_idField = value;
                this.RaisePropertyChanged("channel_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string channel_name {
            get {
                return this.channel_nameField;
            }
            set {
                this.channel_nameField = value;
                this.RaisePropertyChanged("channel_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/api/10/")]
    public partial class click : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long click_idField;
        
        private long visitor_idField;
        
        private long request_session_idField;
        
        private System.DateTime click_dateField;
        
        private string udidField;
        
        private channel channelField;
        
        private source_affiliate source_affiliateField;
        
        private brand_advertiser brand_advertiserField;
        
        private site_offer site_offerField;
        
        private site_offer_contract site_offer_contractField;
        
        private affiliate affiliateField;
        
        private advertiser advertiserField;
        
        private offer offerField;
        
        private offer_contract offer_contractField;
        
        private campaign campaignField;
        
        private creative creativeField;
        
        private string sub_id_1Field;
        
        private string sub_id_2Field;
        
        private string sub_id_3Field;
        
        private string sub_id_4Field;
        
        private string sub_id_5Field;
        
        private string ip_addressField;
        
        private string user_agentField;
        
        private string referrer_urlField;
        
        private string search_termField;
        
        private string request_urlField;
        
        private string redirect_urlField;
        
        private country countryField;
        
        private region regionField;
        
        private language languageField;
        
        private isp ispField;
        
        private device deviceField;
        
        private operating_system operating_systemField;
        
        private browser browserField;
        
        private string dispositionField;
        
        private string paid_actionField;
        
        private payment paidField;
        
        private payment receivedField;
        
        private bool duplicateField;
        
        private int duplicate_clicksField;
        
        private int total_clicksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long click_id {
            get {
                return this.click_idField;
            }
            set {
                this.click_idField = value;
                this.RaisePropertyChanged("click_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long visitor_id {
            get {
                return this.visitor_idField;
            }
            set {
                this.visitor_idField = value;
                this.RaisePropertyChanged("visitor_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long request_session_id {
            get {
                return this.request_session_idField;
            }
            set {
                this.request_session_idField = value;
                this.RaisePropertyChanged("request_session_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime click_date {
            get {
                return this.click_dateField;
            }
            set {
                this.click_dateField = value;
                this.RaisePropertyChanged("click_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string udid {
            get {
                return this.udidField;
            }
            set {
                this.udidField = value;
                this.RaisePropertyChanged("udid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public channel channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
                this.RaisePropertyChanged("channel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public source_affiliate source_affiliate {
            get {
                return this.source_affiliateField;
            }
            set {
                this.source_affiliateField = value;
                this.RaisePropertyChanged("source_affiliate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public brand_advertiser brand_advertiser {
            get {
                return this.brand_advertiserField;
            }
            set {
                this.brand_advertiserField = value;
                this.RaisePropertyChanged("brand_advertiser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public site_offer site_offer {
            get {
                return this.site_offerField;
            }
            set {
                this.site_offerField = value;
                this.RaisePropertyChanged("site_offer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public site_offer_contract site_offer_contract {
            get {
                return this.site_offer_contractField;
            }
            set {
                this.site_offer_contractField = value;
                this.RaisePropertyChanged("site_offer_contract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public affiliate affiliate {
            get {
                return this.affiliateField;
            }
            set {
                this.affiliateField = value;
                this.RaisePropertyChanged("affiliate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public advertiser advertiser {
            get {
                return this.advertiserField;
            }
            set {
                this.advertiserField = value;
                this.RaisePropertyChanged("advertiser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public offer offer {
            get {
                return this.offerField;
            }
            set {
                this.offerField = value;
                this.RaisePropertyChanged("offer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public offer_contract offer_contract {
            get {
                return this.offer_contractField;
            }
            set {
                this.offer_contractField = value;
                this.RaisePropertyChanged("offer_contract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public campaign campaign {
            get {
                return this.campaignField;
            }
            set {
                this.campaignField = value;
                this.RaisePropertyChanged("campaign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public creative creative {
            get {
                return this.creativeField;
            }
            set {
                this.creativeField = value;
                this.RaisePropertyChanged("creative");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string sub_id_1 {
            get {
                return this.sub_id_1Field;
            }
            set {
                this.sub_id_1Field = value;
                this.RaisePropertyChanged("sub_id_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string sub_id_2 {
            get {
                return this.sub_id_2Field;
            }
            set {
                this.sub_id_2Field = value;
                this.RaisePropertyChanged("sub_id_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string sub_id_3 {
            get {
                return this.sub_id_3Field;
            }
            set {
                this.sub_id_3Field = value;
                this.RaisePropertyChanged("sub_id_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string sub_id_4 {
            get {
                return this.sub_id_4Field;
            }
            set {
                this.sub_id_4Field = value;
                this.RaisePropertyChanged("sub_id_4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string sub_id_5 {
            get {
                return this.sub_id_5Field;
            }
            set {
                this.sub_id_5Field = value;
                this.RaisePropertyChanged("sub_id_5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string ip_address {
            get {
                return this.ip_addressField;
            }
            set {
                this.ip_addressField = value;
                this.RaisePropertyChanged("ip_address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string user_agent {
            get {
                return this.user_agentField;
            }
            set {
                this.user_agentField = value;
                this.RaisePropertyChanged("user_agent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string referrer_url {
            get {
                return this.referrer_urlField;
            }
            set {
                this.referrer_urlField = value;
                this.RaisePropertyChanged("referrer_url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string search_term {
            get {
                return this.search_termField;
            }
            set {
                this.search_termField = value;
                this.RaisePropertyChanged("search_term");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string request_url {
            get {
                return this.request_urlField;
            }
            set {
                this.request_urlField = value;
                this.RaisePropertyChanged("request_url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string redirect_url {
            get {
                return this.redirect_urlField;
            }
            set {
                this.redirect_urlField = value;
                this.RaisePropertyChanged("redirect_url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public country country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public region region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public language language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public isp isp {
            get {
                return this.ispField;
            }
            set {
                this.ispField = value;
                this.RaisePropertyChanged("isp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public device device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
                this.RaisePropertyChanged("device");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public operating_system operating_system {
            get {
                return this.operating_systemField;
            }
            set {
                this.operating_systemField = value;
                this.RaisePropertyChanged("operating_system");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public browser browser {
            get {
                return this.browserField;
            }
            set {
                this.browserField = value;
                this.RaisePropertyChanged("browser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string disposition {
            get {
                return this.dispositionField;
            }
            set {
                this.dispositionField = value;
                this.RaisePropertyChanged("disposition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string paid_action {
            get {
                return this.paid_actionField;
            }
            set {
                this.paid_actionField = value;
                this.RaisePropertyChanged("paid_action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public payment paid {
            get {
                return this.paidField;
            }
            set {
                this.paidField = value;
                this.RaisePropertyChanged("paid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public payment received {
            get {
                return this.receivedField;
            }
            set {
                this.receivedField = value;
                this.RaisePropertyChanged("received");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public bool duplicate {
            get {
                return this.duplicateField;
            }
            set {
                this.duplicateField = value;
                this.RaisePropertyChanged("duplicate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public int duplicate_clicks {
            get {
                return this.duplicate_clicksField;
            }
            set {
                this.duplicate_clicksField = value;
                this.RaisePropertyChanged("duplicate_clicks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public int total_clicks {
            get {
                return this.total_clicksField;
            }
            set {
                this.total_clicksField = value;
                this.RaisePropertyChanged("total_clicks");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class advertiser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int advertiser_idField;
        
        private string advertiser_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int advertiser_id {
            get {
                return this.advertiser_idField;
            }
            set {
                this.advertiser_idField = value;
                this.RaisePropertyChanged("advertiser_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string advertiser_name {
            get {
                return this.advertiser_nameField;
            }
            set {
                this.advertiser_nameField = value;
                this.RaisePropertyChanged("advertiser_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class offer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int offer_idField;
        
        private string offer_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int offer_id {
            get {
                return this.offer_idField;
            }
            set {
                this.offer_idField = value;
                this.RaisePropertyChanged("offer_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string offer_name {
            get {
                return this.offer_nameField;
            }
            set {
                this.offer_nameField = value;
                this.RaisePropertyChanged("offer_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class offer_contract : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int offer_contract_idField;
        
        private string offer_contract_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int offer_contract_id {
            get {
                return this.offer_contract_idField;
            }
            set {
                this.offer_contract_idField = value;
                this.RaisePropertyChanged("offer_contract_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string offer_contract_name {
            get {
                return this.offer_contract_nameField;
            }
            set {
                this.offer_contract_nameField = value;
                this.RaisePropertyChanged("offer_contract_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class creative : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int creative_idField;
        
        private string creative_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int creative_id {
            get {
                return this.creative_idField;
            }
            set {
                this.creative_idField = value;
                this.RaisePropertyChanged("creative_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string creative_name {
            get {
                return this.creative_nameField;
            }
            set {
                this.creative_nameField = value;
                this.RaisePropertyChanged("creative_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class country : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string country_codeField;
        
        private string country_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string country_code {
            get {
                return this.country_codeField;
            }
            set {
                this.country_codeField = value;
                this.RaisePropertyChanged("country_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string country_name {
            get {
                return this.country_nameField;
            }
            set {
                this.country_nameField = value;
                this.RaisePropertyChanged("country_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class region : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string region_codeField;
        
        private string region_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string region_code {
            get {
                return this.region_codeField;
            }
            set {
                this.region_codeField = value;
                this.RaisePropertyChanged("region_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string region_name {
            get {
                return this.region_nameField;
            }
            set {
                this.region_nameField = value;
                this.RaisePropertyChanged("region_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class language : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte language_idField;
        
        private string language_nameField;
        
        private string language_abbrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public byte language_id {
            get {
                return this.language_idField;
            }
            set {
                this.language_idField = value;
                this.RaisePropertyChanged("language_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string language_name {
            get {
                return this.language_nameField;
            }
            set {
                this.language_nameField = value;
                this.RaisePropertyChanged("language_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string language_abbr {
            get {
                return this.language_abbrField;
            }
            set {
                this.language_abbrField = value;
                this.RaisePropertyChanged("language_abbr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class isp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int isp_idField;
        
        private string isp_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int isp_id {
            get {
                return this.isp_idField;
            }
            set {
                this.isp_idField = value;
                this.RaisePropertyChanged("isp_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string isp_name {
            get {
                return this.isp_nameField;
            }
            set {
                this.isp_nameField = value;
                this.RaisePropertyChanged("isp_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class device : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short device_idField;
        
        private string device_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short device_id {
            get {
                return this.device_idField;
            }
            set {
                this.device_idField = value;
                this.RaisePropertyChanged("device_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string device_name {
            get {
                return this.device_nameField;
            }
            set {
                this.device_nameField = value;
                this.RaisePropertyChanged("device_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/api/10/")]
    public partial class operating_system : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte operating_system_idField;
        
        private string operating_system_nameField;
        
        private version operating_system_versionField;
        
        private version operating_system_version_minorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public byte operating_system_id {
            get {
                return this.operating_system_idField;
            }
            set {
                this.operating_system_idField = value;
                this.RaisePropertyChanged("operating_system_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string operating_system_name {
            get {
                return this.operating_system_nameField;
            }
            set {
                this.operating_system_nameField = value;
                this.RaisePropertyChanged("operating_system_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public version operating_system_version {
            get {
                return this.operating_system_versionField;
            }
            set {
                this.operating_system_versionField = value;
                this.RaisePropertyChanged("operating_system_version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public version operating_system_version_minor {
            get {
                return this.operating_system_version_minorField;
            }
            set {
                this.operating_system_version_minorField = value;
                this.RaisePropertyChanged("operating_system_version_minor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class version : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short version_idField;
        
        private string version_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short version_id {
            get {
                return this.version_idField;
            }
            set {
                this.version_idField = value;
                this.RaisePropertyChanged("version_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string version_name {
            get {
                return this.version_nameField;
            }
            set {
                this.version_nameField = value;
                this.RaisePropertyChanged("version_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/api/10/")]
    public partial class browser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte browser_idField;
        
        private string browser_nameField;
        
        private version browser_versionField;
        
        private version browser_version_minorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public byte browser_id {
            get {
                return this.browser_idField;
            }
            set {
                this.browser_idField = value;
                this.RaisePropertyChanged("browser_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string browser_name {
            get {
                return this.browser_nameField;
            }
            set {
                this.browser_nameField = value;
                this.RaisePropertyChanged("browser_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public version browser_version {
            get {
                return this.browser_versionField;
            }
            set {
                this.browser_versionField = value;
                this.RaisePropertyChanged("browser_version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public version browser_version_minor {
            get {
                return this.browser_version_minorField;
            }
            set {
                this.browser_version_minorField = value;
                this.RaisePropertyChanged("browser_version_minor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/api/10/")]
    public partial class payment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte currency_idField;
        
        private decimal amountField;
        
        private string formatted_amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public byte currency_id {
            get {
                return this.currency_idField;
            }
            set {
                this.currency_idField = value;
                this.RaisePropertyChanged("currency_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string formatted_amount {
            get {
                return this.formatted_amountField;
            }
            set {
                this.formatted_amountField = value;
                this.RaisePropertyChanged("formatted_amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class campaign_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte campaign_type_idField;
        
        private string campaign_type_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public byte campaign_type_id {
            get {
                return this.campaign_type_idField;
            }
            set {
                this.campaign_type_idField = value;
                this.RaisePropertyChanged("campaign_type_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string campaign_type_name {
            get {
                return this.campaign_type_nameField;
            }
            set {
                this.campaign_type_nameField = value;
                this.RaisePropertyChanged("campaign_type_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class disposition_type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte disposition_type_idField;
        
        private string disposition_type_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public byte disposition_type_id {
            get {
                return this.disposition_type_idField;
            }
            set {
                this.disposition_type_idField = value;
                this.RaisePropertyChanged("disposition_type_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string disposition_type_name {
            get {
                return this.disposition_type_nameField;
            }
            set {
                this.disposition_type_nameField = value;
                this.RaisePropertyChanged("disposition_type_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/api/10/")]
    public partial class disposition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short disposition_idField;
        
        private string disposition_nameField;
        
        private disposition_type disposition_typeField;
        
        private string contactField;
        
        private System.DateTime disposition_dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short disposition_id {
            get {
                return this.disposition_idField;
            }
            set {
                this.disposition_idField = value;
                this.RaisePropertyChanged("disposition_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string disposition_name {
            get {
                return this.disposition_nameField;
            }
            set {
                this.disposition_nameField = value;
                this.RaisePropertyChanged("disposition_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public disposition_type disposition_type {
            get {
                return this.disposition_typeField;
            }
            set {
                this.disposition_typeField = value;
                this.RaisePropertyChanged("disposition_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
                this.RaisePropertyChanged("contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime disposition_date {
            get {
                return this.disposition_dateField;
            }
            set {
                this.disposition_dateField = value;
                this.RaisePropertyChanged("disposition_date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(get_response))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(click_report_response))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(conversion_report_response))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/api/10/")]
    public partial class base_response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(click_report_response))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(conversion_report_response))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/api/10/")]
    public partial class get_response : base_response {
        
        private int row_countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int row_count {
            get {
                return this.row_countField;
            }
            set {
                this.row_countField = value;
                this.RaisePropertyChanged("row_count");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/api/10/")]
    public partial class click_report_response : get_response {
        
        private click[] clicksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public click[] clicks {
            get {
                return this.clicksField;
            }
            set {
                this.clicksField = value;
                this.RaisePropertyChanged("clicks");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface reportsSoapChannel : IpJobs.CakeV10.reportsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class reportsSoapClient : System.ServiceModel.ClientBase<IpJobs.CakeV10.reportsSoap>, IpJobs.CakeV10.reportsSoap {
        
        public reportsSoapClient() {
        }
        
        public reportsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public reportsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public reportsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public reportsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IpJobs.CakeV10.conversion_report_response Conversions(string api_key, System.DateTime start_date, System.DateTime end_date, int affiliate_id, int advertiser_id, int offer_id, int campaign_id, int creative_id, bool include_tests, int start_at_row, int row_limit, IpJobs.CakeV10.ConversionsSortFields sort_field, bool sort_descending) {
            return base.Channel.Conversions(api_key, start_date, end_date, affiliate_id, advertiser_id, offer_id, campaign_id, creative_id, include_tests, start_at_row, row_limit, sort_field, sort_descending);
        }
        
        public System.Threading.Tasks.Task<IpJobs.CakeV10.conversion_report_response> ConversionsAsync(string api_key, System.DateTime start_date, System.DateTime end_date, int affiliate_id, int advertiser_id, int offer_id, int campaign_id, int creative_id, bool include_tests, int start_at_row, int row_limit, IpJobs.CakeV10.ConversionsSortFields sort_field, bool sort_descending) {
            return base.Channel.ConversionsAsync(api_key, start_date, end_date, affiliate_id, advertiser_id, offer_id, campaign_id, creative_id, include_tests, start_at_row, row_limit, sort_field, sort_descending);
        }
        
        public IpJobs.CakeV10.conversion_report_response ConversionChanges(string api_key, System.DateTime changes_since, bool include_new_conversions, int affiliate_id, int advertiser_id, int offer_id, int campaign_id, int creative_id, bool include_tests, int start_at_row, int row_limit, IpJobs.CakeV10.ConversionsSortFields sort_field, bool sort_descending) {
            return base.Channel.ConversionChanges(api_key, changes_since, include_new_conversions, affiliate_id, advertiser_id, offer_id, campaign_id, creative_id, include_tests, start_at_row, row_limit, sort_field, sort_descending);
        }
        
        public System.Threading.Tasks.Task<IpJobs.CakeV10.conversion_report_response> ConversionChangesAsync(string api_key, System.DateTime changes_since, bool include_new_conversions, int affiliate_id, int advertiser_id, int offer_id, int campaign_id, int creative_id, bool include_tests, int start_at_row, int row_limit, IpJobs.CakeV10.ConversionsSortFields sort_field, bool sort_descending) {
            return base.Channel.ConversionChangesAsync(api_key, changes_since, include_new_conversions, affiliate_id, advertiser_id, offer_id, campaign_id, creative_id, include_tests, start_at_row, row_limit, sort_field, sort_descending);
        }
        
        public IpJobs.CakeV10.click_report_response Clicks(string api_key, System.DateTime start_date, System.DateTime end_date, int affiliate_id, int advertiser_id, int offer_id, int campaign_id, int creative_id, byte price_format_id, bool include_duplicates, bool include_tests, int start_at_row, int row_limit) {
            return base.Channel.Clicks(api_key, start_date, end_date, affiliate_id, advertiser_id, offer_id, campaign_id, creative_id, price_format_id, include_duplicates, include_tests, start_at_row, row_limit);
        }
        
        public System.Threading.Tasks.Task<IpJobs.CakeV10.click_report_response> ClicksAsync(string api_key, System.DateTime start_date, System.DateTime end_date, int affiliate_id, int advertiser_id, int offer_id, int campaign_id, int creative_id, byte price_format_id, bool include_duplicates, bool include_tests, int start_at_row, int row_limit) {
            return base.Channel.ClicksAsync(api_key, start_date, end_date, affiliate_id, advertiser_id, offer_id, campaign_id, creative_id, price_format_id, include_duplicates, include_tests, start_at_row, row_limit);
        }
    }
}
