import React from "react"

export const routes = {
  login: {
    abs: "/login",
    component: React.lazy(() => import("../../views/login")),
    description: "",
    title: "Home",
    iconType: "home",
    path: "login",
    redirectFrom: ["/"],
    requiresAuthentication: false as const,
    subroutes: {},
  },

  dashboard: {
    abs: "/dashboard",
    component: React.lazy(() => import("../../themes/ant-default")),
    description: "",
    title: "Dashboard",
    iconType: "dashboard",
    path: "dashboard",
    redirectFrom: [],
    requiresAuthentication: true as const,
    subroutes: {
      summary: {
        abs: "/dashboard/summary",
        component: React.lazy(() => import("../../themes/ant-default/views/summary")),
        description: "Customizable highlights dashboard",
        title: "Summary",
        iconType: "dashboard",
        path: "summary",
        redirectFrom: ["/dashboard"],
        requiresAuthentication: true as const,
        subroutes: {
          "/": {
            abs: "/dashboard/summary",
            component: React.lazy(() => import("../../themes/ant-default/views/summary/routes/SummaryView")),
            description: "",
            title: "Summary",
            iconType: "dashboard",
            path: "/",
            redirectFrom: [],
            requiresAuthentication: true as const,
            subroutes: {},
          },
        },
      },
      reports: {
        abs: "/dashboard/reports",
        component: React.lazy(() => import("../../themes/ant-default/views/reports")),
        description: "Generate and export reports",
        title: "Reports",
        iconType: "table",
        path: "reports",
        redirectFrom: [],
        requiresAuthentication: true as const,
        subroutes: {
          reports: {
            abs: "/dashboard/reports/:reportId",
            component: React.lazy(() => import("../../themes/ant-default/views/reports/routes/report")),
            description: "Application Report",
            title: "Reports",
            iconType: "bar-chart",
            path: ":reportId",
            redirectFrom: [],
            requiresAuthentication: true as const,
            subroutes: {},
          },
          "import-ingestion": {
            abs: "/dashboard/reports/import-ingestion",
            component: React.lazy(() => import("../../themes/ant-default/views/reports/routes/import-ingestion")),
            description: "Import Ingestion Live Report",
            title: "Import Ingestion",
            iconType: "bar-chart",
            path: "import-ingestion",
            redirectFrom: [],
            requiresAuthentication: true as const,
            subroutes: {},
          },
        },
      },
      apps: {
        abs: "/dashboard/apps",
        component: React.lazy(() => import("../../themes/ant-default/views/business-application")),
        description: "Manage On Point Business Applications",
        title: "Business Applications",
        iconType: "deployment-unit",
        path: "apps",
        redirectFrom: [],
        requiresAuthentication: true as const,
        subroutes: {
          ":id": {
            abs: `/dashboard/apps/:id`,
            component: React.lazy(() => import("../../themes/ant-default/views/business-application")),
            description: "",
            title: "Business App",
            iconType: "appstore",
            path: `:id`,
            redirectFrom: [],
            requiresAuthentication: true as const,
            subroutes: {
              ":pageId": {
                abs: `/dashboard/apps/:id/:pageId`,
                component: React.lazy(() => import("../../themes/ant-default/views/business-application")),
                description: "",
                title: "Business App Page",
                iconType: "appstore",
                path: `:pageId`,
                redirectFrom: [],
                requiresAuthentication: true as const,
                subroutes: {},
              },
            },
          },
        },
      },
      "global-config": {
        abs: "/dashboard/global-config",
        component: React.lazy(() => import("../../themes/ant-default/views/global-config")),
        description: "Manage GlobalConfig.Config entries",
        title: "Global Config",
        iconType: "code",
        path: "global-config",
        redirectFrom: [],
        requiresAuthentication: true as const,
        subroutes: {
          "/": {
            abs: "/dashboard/global-config",
            component: React.lazy(() => import("../../themes/ant-default/views/global-config/routes/list")),
            description: "",
            title: "Global Configs Index",
            iconType: "code",
            path: "/",
            redirectFrom: [],
            requiresAuthentication: true as const,
            subroutes: {},
          },
          create: {
            abs: "/dashboard/global-config/create",
            component: React.lazy(() => import("../../themes/ant-default/views/global-config/routes/create")),
            description: "",
            title: "Create Global Config",
            iconType: "code",
            path: "create",
            redirectFrom: [],
            requiresAuthentication: true as const,
            subroutes: {},
          },
          ":configId/edit": {
            abs: "/dashboard/global-config/:configId/edit",
            component: React.lazy(() => import("../../themes/ant-default/views/global-config/routes/edit")),
            description: "",
            title: "Edit Global Config",
            iconType: "code",
            path: ":configId/edit",
            redirectFrom: [],
            requiresAuthentication: true as const,
            subroutes: {},
          },
          ":configId": {
            abs: "/dashboard/global-config/:configId",
            component: React.lazy(() => import("../../themes/ant-default/views/global-config/routes/show")),
            description: "",
            title: "Global Configs Index",
            iconType: "code",
            path: ":configId",
            redirectFrom: [],
            requiresAuthentication: true as const,
            subroutes: {},
          },
        },
      },
    },
  },
}
