import { ComponentDefinition } from "@opg/interface-builder"

export const editColumnComponents: ComponentDefinition[] = [
  {
    key: "columns",
    valueKey: "columns",
    label: "Columns",
    hideLabel: true,
    addItemLabel: "Add Column",
    component: "list",
    emptyText: "No Configured Columns",
    orientation: "horizontal",
    preconfigured: true,
    getRootUserInterfaceData: () => void 0,
    onChangeRootData: () => void 0,
    incomingEventHandlers: [],
    outgoingEventMap: {},
    components: [
      {
        key: "column",
        component: "container",
        label: "Column",
        hideLabel: true,
        preconfigured: true,
        size: "small",
        style: "&.container { padding: 5px; }",
        components: [
          {
            key: "name",
            valueKey: "name",
            label: "Name",
            component: "input",
            size: "small",
          },
          {
            key: "caption",
            valueKey: "caption",
            label: "Caption",
            component: "input",
            size: "small",
          },
        ],
      },
    ],
  },
  {
    key: "rows",
    valueKey: "rows",
    label: "Rows",
    hideLabel: true,
    addItemLabel: "Add Row",
    component: "list",
    emptyText: "No Configured Rows",
    orientation: "horizontal",
    preconfigured: true,
    getRootUserInterfaceData: () => void 0,
    onChangeRootData: () => void 0,
    incomingEventHandlers: [],
    outgoingEventMap: {},
    components: [
      {
        key: "row",
        component: "container",
        label: "Row",
        hideLabel: true,
        preconfigured: true,
        size: "small",
        style: "&.container { padding: 5px; }",
        components: [
          {
            key: "name",
            valueKey: "name",
            label: "Name",
            component: "input",
            size: "small",
          },
        ],
      },
    ],
  },
  {
    key: "values",
    valueKey: "values",
    label: "Values",
    hideLabel: true,
    addItemLabel: "Add Value",
    component: "list",
    emptyText: "No Configured Values",
    orientation: "horizontal",
    preconfigured: true,
    getRootUserInterfaceData: () => void 0,
    onChangeRootData: () => void 0,
    incomingEventHandlers: [],
    outgoingEventMap: {},
    components: [
      {
        key: "value",
        component: "container",
        label: "Value",
        hideLabel: true,
        preconfigured: true,
        size: "small",
        style: "&.container { padding: 5px; }",
        components: [
          {
            key: "name",
            valueKey: "name",
            label: "Name",
            component: "input",
            size: "small",
          },
          {
            key: "caption",
            valueKey: "caption",
            label: "Caption",
            component: "input",
            size: "small",
          },
        ],
      },
    ],
  },
]
