export const appDescription: string
export const appLogo: string
export const appLogoCollapsed: string
export const appsMenuIcon: string
export const appsMenuItem: string
export const appsMenuPopover: string
export const breadCrumbsRow: string
export const header: string
export const headerRightPanel: string
export const layoutContainer: string
export const menuSearchButton: string
export const sidebar: string
export const sidebarToggleButton: string
export const title: string
export const userAvatar: string
