export const API_RESULT_CODES = {
  0: "Success",
  1: "Unhandled exception",
  2: "Server resource exception - Some external resource such as the DB or required API is down",
  50: "Bad or missing SID - this should never be shown as such",
  100: "Function unhandled exception",
  101: "Incorrect confirmation code",
  102: "Badly formatted contact",
  103: "Sending message to contact is not supported",
  104: "Password rule violation",
  105: "Handle rule violation",
  106: "Invalid login",
  107: "Account exists",
  108: "Exhausted unique handle attempts",
  109: "Contact not found",
  110: "Name already used in context",
  111: "Invalid promotion payload",
  500: "GetGot is currently under maintenance. Please try again in a few minutes.",
}