//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaingTemplate
    {
        public int id { get; set; }
        public string name { get; set; }
        public string subject { get; set; }
        public string html { get; set; }
        public string text { get; set; }
        public bool active { get; set; }
        public int campaignid { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> dtcreated { get; set; }
        public Nullable<System.DateTime> dtmodified { get; set; }
        public Nullable<int> countsent { get; set; }
        public Nullable<bool> is250ok { get; set; }
        public string friendlyName { get; set; }
        public string type { get; set; }
        public Nullable<int> classification { get; set; }
    
        public virtual Campaign Campaign { get; set; }
    }
}
