//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campaign()
        {
            this.CampaingTemplates = new HashSet<CampaingTemplate>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public int leadage { get; set; }
        public string sendstatus { get; set; }
        public string domainid { get; set; }
        public System.DateTime dtstart { get; set; }
        public System.TimeSpan stime { get; set; }
        public Nullable<System.TimeSpan> etime { get; set; }
        public int scheduletype { get; set; }
        public bool active { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> dtcreated { get; set; }
        public Nullable<System.DateTime> dtmodified { get; set; }
        public int credential_id { get; set; }
        public Nullable<int> emailog_campaign { get; set; }
        public Nullable<int> audience_id { get; set; }
        public Nullable<int> delay { get; set; }
        public Nullable<System.DateTime> dtstartopeners { get; set; }
        public Nullable<System.DateTime> dtendopeners { get; set; }
        public Nullable<int> limitperday { get; set; }
        public Nullable<bool> blockpacer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaingTemplate> CampaingTemplates { get; set; }
    }
}
