export const appDescription: string
export const appIcon: string
export const appTitle: string
export const header: string
export const headerRightPanel: string
export const selected: string
export const sidebarToggle: string
export const sidebarToggleIcon: string
export const userAvatar: string
