//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeIntegration.CakeV9 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cakemarketing.com/affiliates/api/9/", ConfigurationName="CakeV9.reportsSoap")]
    public interface reportsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cakemarketing.com/affiliates/api/9/Clicks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(base_response))]
        CakeIntegration.CakeV9.click_response Clicks(string api_key, int affiliate_id, System.DateTime start_date, System.DateTime end_date, int offer_id, int campaign_id, bool include_duplicates, int start_at_row, int row_limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cakemarketing.com/affiliates/api/9/Clicks", ReplyAction="*")]
        System.Threading.Tasks.Task<CakeIntegration.CakeV9.click_response> ClicksAsync(string api_key, int affiliate_id, System.DateTime start_date, System.DateTime end_date, int offer_id, int campaign_id, bool include_duplicates, int start_at_row, int row_limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cakemarketing.com/affiliates/api/9/EventConversions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(base_response))]
        CakeIntegration.CakeV9.event_conversion_response EventConversions(string api_key, int affiliate_id, System.DateTime start_date, System.DateTime end_date, int site_offer_id, byte currency_id, string disposition_type, CakeIntegration.CakeV9.event_type event_type, bool exclude_bot_traffic, int start_at_row, int row_limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cakemarketing.com/affiliates/api/9/EventConversions", ReplyAction="*")]
        System.Threading.Tasks.Task<CakeIntegration.CakeV9.event_conversion_response> EventConversionsAsync(string api_key, int affiliate_id, System.DateTime start_date, System.DateTime end_date, int site_offer_id, byte currency_id, string disposition_type, CakeIntegration.CakeV9.event_type event_type, bool exclude_bot_traffic, int start_at_row, int row_limit);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/affiliates/api/9/")]
    public partial class click_response : get_response {
        
        private click[] clicksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public click[] clicks {
            get {
                return this.clicksField;
            }
            set {
                this.clicksField = value;
                this.RaisePropertyChanged("clicks");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/affiliates/api/9/")]
    public partial class click : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long request_session_idField;
        
        private System.DateTime click_dateField;
        
        private offer offerField;
        
        private offer redirect_from_offerField;
        
        private int campaign_idField;
        
        private string subid_1Field;
        
        private string subid_2Field;
        
        private string subid_3Field;
        
        private string subid_4Field;
        
        private string subid_5Field;
        
        private string ip_addressField;
        
        private string paid_actionField;
        
        private System.Nullable<decimal> priceField;
        
        private bool duplicateField;
        
        private int duplicate_clicksField;
        
        private System.Nullable<System.DateTime> original_click_dateField;
        
        private long unique_click_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long request_session_id {
            get {
                return this.request_session_idField;
            }
            set {
                this.request_session_idField = value;
                this.RaisePropertyChanged("request_session_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime click_date {
            get {
                return this.click_dateField;
            }
            set {
                this.click_dateField = value;
                this.RaisePropertyChanged("click_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public offer offer {
            get {
                return this.offerField;
            }
            set {
                this.offerField = value;
                this.RaisePropertyChanged("offer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public offer redirect_from_offer {
            get {
                return this.redirect_from_offerField;
            }
            set {
                this.redirect_from_offerField = value;
                this.RaisePropertyChanged("redirect_from_offer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int campaign_id {
            get {
                return this.campaign_idField;
            }
            set {
                this.campaign_idField = value;
                this.RaisePropertyChanged("campaign_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string subid_1 {
            get {
                return this.subid_1Field;
            }
            set {
                this.subid_1Field = value;
                this.RaisePropertyChanged("subid_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string subid_2 {
            get {
                return this.subid_2Field;
            }
            set {
                this.subid_2Field = value;
                this.RaisePropertyChanged("subid_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string subid_3 {
            get {
                return this.subid_3Field;
            }
            set {
                this.subid_3Field = value;
                this.RaisePropertyChanged("subid_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string subid_4 {
            get {
                return this.subid_4Field;
            }
            set {
                this.subid_4Field = value;
                this.RaisePropertyChanged("subid_4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string subid_5 {
            get {
                return this.subid_5Field;
            }
            set {
                this.subid_5Field = value;
                this.RaisePropertyChanged("subid_5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ip_address {
            get {
                return this.ip_addressField;
            }
            set {
                this.ip_addressField = value;
                this.RaisePropertyChanged("ip_address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string paid_action {
            get {
                return this.paid_actionField;
            }
            set {
                this.paid_actionField = value;
                this.RaisePropertyChanged("paid_action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<decimal> price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool duplicate {
            get {
                return this.duplicateField;
            }
            set {
                this.duplicateField = value;
                this.RaisePropertyChanged("duplicate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int duplicate_clicks {
            get {
                return this.duplicate_clicksField;
            }
            set {
                this.duplicate_clicksField = value;
                this.RaisePropertyChanged("duplicate_clicks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<System.DateTime> original_click_date {
            get {
                return this.original_click_dateField;
            }
            set {
                this.original_click_dateField = value;
                this.RaisePropertyChanged("original_click_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public long unique_click_id {
            get {
                return this.unique_click_idField;
            }
            set {
                this.unique_click_idField = value;
                this.RaisePropertyChanged("unique_click_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="API:id_name_store")]
    public partial class offer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int offer_idField;
        
        private string offer_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int offer_id {
            get {
                return this.offer_idField;
            }
            set {
                this.offer_idField = value;
                this.RaisePropertyChanged("offer_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string offer_name {
            get {
                return this.offer_nameField;
            }
            set {
                this.offer_nameField = value;
                this.RaisePropertyChanged("offer_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/affiliates/api/9/")]
    public partial class event_conversion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string macro_event_conversion_idField;
        
        private string order_idField;
        
        private System.Nullable<int> micro_event_idField;
        
        private string micro_event_nameField;
        
        private System.DateTime event_conversion_dateField;
        
        private string storefrontField;
        
        private int site_offer_idField;
        
        private string site_offer_nameField;
        
        private int campaign_idField;
        
        private int creative_idField;
        
        private string creative_nameField;
        
        private string subid_1Field;
        
        private string subid_2Field;
        
        private string subid_3Field;
        
        private string subid_4Field;
        
        private string subid_5Field;
        
        private decimal priceField;
        
        private System.Nullable<decimal> order_totalField;
        
        private string payout_rule_nameField;
        
        private string dispositionField;
        
        private string disposition_typeField;
        
        private bool testField;
        
        private string currency_symbolField;
        
        private string order_currency_symbolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string macro_event_conversion_id {
            get {
                return this.macro_event_conversion_idField;
            }
            set {
                this.macro_event_conversion_idField = value;
                this.RaisePropertyChanged("macro_event_conversion_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string order_id {
            get {
                return this.order_idField;
            }
            set {
                this.order_idField = value;
                this.RaisePropertyChanged("order_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> micro_event_id {
            get {
                return this.micro_event_idField;
            }
            set {
                this.micro_event_idField = value;
                this.RaisePropertyChanged("micro_event_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string micro_event_name {
            get {
                return this.micro_event_nameField;
            }
            set {
                this.micro_event_nameField = value;
                this.RaisePropertyChanged("micro_event_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime event_conversion_date {
            get {
                return this.event_conversion_dateField;
            }
            set {
                this.event_conversion_dateField = value;
                this.RaisePropertyChanged("event_conversion_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string storefront {
            get {
                return this.storefrontField;
            }
            set {
                this.storefrontField = value;
                this.RaisePropertyChanged("storefront");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int site_offer_id {
            get {
                return this.site_offer_idField;
            }
            set {
                this.site_offer_idField = value;
                this.RaisePropertyChanged("site_offer_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string site_offer_name {
            get {
                return this.site_offer_nameField;
            }
            set {
                this.site_offer_nameField = value;
                this.RaisePropertyChanged("site_offer_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int campaign_id {
            get {
                return this.campaign_idField;
            }
            set {
                this.campaign_idField = value;
                this.RaisePropertyChanged("campaign_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int creative_id {
            get {
                return this.creative_idField;
            }
            set {
                this.creative_idField = value;
                this.RaisePropertyChanged("creative_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string creative_name {
            get {
                return this.creative_nameField;
            }
            set {
                this.creative_nameField = value;
                this.RaisePropertyChanged("creative_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string subid_1 {
            get {
                return this.subid_1Field;
            }
            set {
                this.subid_1Field = value;
                this.RaisePropertyChanged("subid_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string subid_2 {
            get {
                return this.subid_2Field;
            }
            set {
                this.subid_2Field = value;
                this.RaisePropertyChanged("subid_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string subid_3 {
            get {
                return this.subid_3Field;
            }
            set {
                this.subid_3Field = value;
                this.RaisePropertyChanged("subid_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string subid_4 {
            get {
                return this.subid_4Field;
            }
            set {
                this.subid_4Field = value;
                this.RaisePropertyChanged("subid_4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string subid_5 {
            get {
                return this.subid_5Field;
            }
            set {
                this.subid_5Field = value;
                this.RaisePropertyChanged("subid_5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<decimal> order_total {
            get {
                return this.order_totalField;
            }
            set {
                this.order_totalField = value;
                this.RaisePropertyChanged("order_total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string payout_rule_name {
            get {
                return this.payout_rule_nameField;
            }
            set {
                this.payout_rule_nameField = value;
                this.RaisePropertyChanged("payout_rule_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string disposition {
            get {
                return this.dispositionField;
            }
            set {
                this.dispositionField = value;
                this.RaisePropertyChanged("disposition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string disposition_type {
            get {
                return this.disposition_typeField;
            }
            set {
                this.disposition_typeField = value;
                this.RaisePropertyChanged("disposition_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
                this.RaisePropertyChanged("test");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string currency_symbol {
            get {
                return this.currency_symbolField;
            }
            set {
                this.currency_symbolField = value;
                this.RaisePropertyChanged("currency_symbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string order_currency_symbol {
            get {
                return this.order_currency_symbolField;
            }
            set {
                this.order_currency_symbolField = value;
                this.RaisePropertyChanged("order_currency_symbol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/affiliates/api/9/")]
    public partial class event_conversion_summary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal priceField;
        
        private System.Nullable<decimal> order_totalField;
        
        private string currency_symbolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> order_total {
            get {
                return this.order_totalField;
            }
            set {
                this.order_totalField = value;
                this.RaisePropertyChanged("order_total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string currency_symbol {
            get {
                return this.currency_symbolField;
            }
            set {
                this.currency_symbolField = value;
                this.RaisePropertyChanged("currency_symbol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(get_response))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(event_conversion_response))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(click_response))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/affiliates/api/9/")]
    public partial class base_response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(event_conversion_response))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(click_response))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/affiliates/api/9/")]
    public partial class get_response : base_response {
        
        private int row_countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int row_count {
            get {
                return this.row_countField;
            }
            set {
                this.row_countField = value;
                this.RaisePropertyChanged("row_count");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/affiliates/api/9/")]
    public partial class event_conversion_response : get_response {
        
        private event_conversion_summary summaryField;
        
        private event_conversion[] event_conversionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public event_conversion_summary summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
                this.RaisePropertyChanged("summary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public event_conversion[] event_conversions {
            get {
                return this.event_conversionsField;
            }
            set {
                this.event_conversionsField = value;
                this.RaisePropertyChanged("event_conversions");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cakemarketing.com/affiliates/api/9/")]
    public enum event_type {
        
        /// <remarks/>
        all,
        
        /// <remarks/>
        micro_events,
        
        /// <remarks/>
        macro_event_conversions,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface reportsSoapChannel : CakeIntegration.CakeV9.reportsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class reportsSoapClient : System.ServiceModel.ClientBase<CakeIntegration.CakeV9.reportsSoap>, CakeIntegration.CakeV9.reportsSoap {
        
        public reportsSoapClient() {
        }
        
        public reportsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public reportsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public reportsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public reportsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CakeIntegration.CakeV9.click_response Clicks(string api_key, int affiliate_id, System.DateTime start_date, System.DateTime end_date, int offer_id, int campaign_id, bool include_duplicates, int start_at_row, int row_limit) {
            return base.Channel.Clicks(api_key, affiliate_id, start_date, end_date, offer_id, campaign_id, include_duplicates, start_at_row, row_limit);
        }
        
        public System.Threading.Tasks.Task<CakeIntegration.CakeV9.click_response> ClicksAsync(string api_key, int affiliate_id, System.DateTime start_date, System.DateTime end_date, int offer_id, int campaign_id, bool include_duplicates, int start_at_row, int row_limit) {
            return base.Channel.ClicksAsync(api_key, affiliate_id, start_date, end_date, offer_id, campaign_id, include_duplicates, start_at_row, row_limit);
        }
        
        public CakeIntegration.CakeV9.event_conversion_response EventConversions(string api_key, int affiliate_id, System.DateTime start_date, System.DateTime end_date, int site_offer_id, byte currency_id, string disposition_type, CakeIntegration.CakeV9.event_type event_type, bool exclude_bot_traffic, int start_at_row, int row_limit) {
            return base.Channel.EventConversions(api_key, affiliate_id, start_date, end_date, site_offer_id, currency_id, disposition_type, event_type, exclude_bot_traffic, start_at_row, row_limit);
        }
        
        public System.Threading.Tasks.Task<CakeIntegration.CakeV9.event_conversion_response> EventConversionsAsync(string api_key, int affiliate_id, System.DateTime start_date, System.DateTime end_date, int site_offer_id, byte currency_id, string disposition_type, CakeIntegration.CakeV9.event_type event_type, bool exclude_bot_traffic, int start_at_row, int row_limit) {
            return base.Channel.EventConversionsAsync(api_key, affiliate_id, start_date, end_date, site_offer_id, currency_id, disposition_type, event_type, exclude_bot_traffic, start_at_row, row_limit);
        }
    }
}
