export const appIcon: string
export const menu: string
export const selected: string
export const sidebar: string
export const sidebarHeader: string
export const sidebarHeaderCollapsed: string
export const sidebarHeaderIcon: string
export const sidebarPinButton: string
export const sidebarTitle: string
export const sidebarToggle: string
