// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_rename_seedbucket_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_rename_seedbucket_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201805111917373_update_rename_seedbucket_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
