// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addclientapikeyseedsbucketuuid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addclientapikeyseedsbucketuuid));
        
        string IMigrationMetadata.Id
        {
            get { return "201802202100161_add-client-apikey-seedsbucket-uuid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
