// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_templateTest_info_to_mail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_templateTest_info_to_mail));
        
        string IMigrationMetadata.Id
        {
            get { return "201806081750550_add_templateTest_info_to_mail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
