// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_smtp_data_provider : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_smtp_data_provider));
        
        string IMigrationMetadata.Id
        {
            get { return "201805021746357_update_smtp_data_provider"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
