export const exportData = [
  {
    id: 113509,
    partnerId: 1,
    table_name: 'onpoint_signal',
    last_id_processed: 13059,
    message: {},
    runtime: 0.2,
    succeeded: true,
    rows_processed: 27644,
  },
  {
    id: 113508,
    partnerId: 2,
    table_name: 'tower_signal',
    last_id_processed: 13059,
    message: {},
    runtime: 0.2,
    succeeded: false,
    rows_processed: 1236,
  },
  {
    id: 113507,
    partnerId: 3,
    table_name: 'lighthouse_signal',
    last_id_processed: 13059,
    message: {},
    runtime: 0.2,
    succeeded: true,
    rows_processed: 1236,
  },
  {
    id: 113506,
    partnerId: 4,
    table_name: 'leadme_signal',
    last_id_processed: 13059,
    message: {},
    runtime: 0.2,
    succeeded: true,
    rows_processed: 1236,
  },
  {
    id: 113505,
    partnerId: 1,
    table_name: 'onpoint_signal',
    last_id_processed: 13059,
    message: {},
    runtime: 0.2,
    succeeded: true,
    rows_processed: 1236,
  },
  {
    id: 113504,
    partnerId: 2,
    table_name: 'tower_signal',
    last_id_processed: 13059,
    message: {},
    runtime: 0.2,
    succeeded: true,
    rows_processed: 1236,
  },
  {
    id: 113503,
    partnerId: 3,
    table_name: 'lighthouse_signal',
    last_id_processed: 13059,
    message: {},
    succeeded: true,
    rows_processed: 1236,
  },
  {
    id: 113502,
    partnerId: 4,
    table_name: 'leadme_signal',
    last_id_processed: 13059,
    message: {},
    runtime: 0.2,
    succeeded: true,
    rows_processed: 1236,
  },
  {
    id: 113501,
    partnerId: 1,
    table_name: 'onpoint_signal',
    last_id_processed: 13059,
    message: {},
    runtime: 0.2,
    succeeded: true,
    rows_processed: "abc",
  },
  {
    id: 113500,
    partnerId: 2,
    table_name: 'tower_signal',
    last_id_processed: 13059,
    message: {},
    runtime: 0.2,
    succeeded: true,
    rows_processed: 1236,
  },
];